version: '3.3'
services: 
    dev: 
        build: ./
        ports:
            - "8000:8000"
        command: npm run dev:server
        volumes:
            - "./:/app"

    server:
        build: ./
        ports:
            - "8000:8000"
        command: npm run prod
        volumes:
            - "./:/app"